sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t shashank/github-react -f Dockerfile.dev .

script:
  - docker run shashank/github-react-react npm run test -- --coverage
